#!/usr/bin/env bash
set -Eeuo pipefail

CLOUD_HOST="${CLOUD_HOST:-101.35.234.4}"
CLOUD_USER="${CLOUD_USER:-root}"
SSH_PORT="${SSH_PORT:-22}"
SSH_IDENTITY_FILE="${SSH_IDENTITY_FILE:-}"
REMOTE_BIND_HOST="${REMOTE_BIND_HOST:-127.0.0.1}"
REMOTE_PORT="${REMOTE_PORT:-18000}"
LOCAL_HOST="${LOCAL_HOST:-127.0.0.1}"
LOCAL_PORT="${LOCAL_PORT:-8000}"
EXIT_ON_FORWARD_FAILURE="${EXIT_ON_FORWARD_FAILURE:-yes}"
SERVER_ALIVE_INTERVAL="${SERVER_ALIVE_INTERVAL:-30}"
SERVER_ALIVE_COUNT_MAX="${SERVER_ALIVE_COUNT_MAX:-3}"

ssh_command=(
  ssh -N
  -p "$SSH_PORT"
  -o "ExitOnForwardFailure=${EXIT_ON_FORWARD_FAILURE}"
  -o "ServerAliveInterval=${SERVER_ALIVE_INTERVAL}"
  -o "ServerAliveCountMax=${SERVER_ALIVE_COUNT_MAX}"
  -R "${REMOTE_BIND_HOST}:${REMOTE_PORT}:${LOCAL_HOST}:${LOCAL_PORT}"
)

if [[ -n "$SSH_IDENTITY_FILE" ]]; then
  ssh_command+=(-i "$SSH_IDENTITY_FILE")
fi

echo "Starting reverse tunnel:"
echo "  cloud ${REMOTE_BIND_HOST}:${REMOTE_PORT} -> AutoDL ${LOCAL_HOST}:${LOCAL_PORT}"
echo "  ssh target: ${CLOUD_USER}@${CLOUD_HOST}:${SSH_PORT}"
exec "${ssh_command[@]}" "${CLOUD_USER}@${CLOUD_HOST}"
